#
# Makefile
#

CIRCLEHOME = ../../..

OBJS = 	app.o \
		audio.o \
		awsLoopTrackButton.o 

MAKE_LIBS = \
	$(CIRCLEHOME)/_prh/ws/libws.mark \
	$(CIRCLEHOME)/_prh/audio/libaudio.mark \
 	$(CIRCLEHOME)/_prh/system/std_kernel.mark \
	$(CIRCLEHOME)/_prh/devices/lib_devices.mark \

include ../../myRules.mk
