#
# Makefile
#

CIRCLEHOME = ../../../

OBJS	= main.o kernel.o btTester.o

# rfcomm.o

MAKE_LIBS = $(CIRCLEHOME)/_prh/bt/libbluetooth.mark \

LIBS = \
	$(CIRCLEHOME)/_prh/bt/libbluetooth.a \
	
include ../../myRules.mk
