#
# Makefile
#

CIRCLEHOME = ../../..

OBJS = kernel.o main.o

MAKE_LIBS = \
	../../devices/libdevices.mark \
	
LIBS	= \
	$(CIRCLEHOME)/lib/libcircle.a \
	../../devices/libdevices.a \


include $(CIRCLEHOME)/Rules.mk
