#
# Makefile
#

CIRCLEHOME = ../../../../../circle

OBJS	= main.o kernel.o  touch_pen.o


LIBS	= \
	$(CIRCLEHOME)/lib/libcircle.a \
	$(CIRCLEHOME)/addon/lcd/liblcd.a \
	$(CIRCLEHOME)/lib/sched/libsched.a \
	

include $(CIRCLEHOME)/Rules.mk
